/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

import javax.swing.Timer;
import service.ConnectionGuard;
import service.ConnectionService;
import service.ConnectionService.Action;


/**
 *
 * @author logon
 */
public class TempoAlugado extends javax.swing.JFrame {

    private Timer timer;
    private int metaSegundo;
    private int metaMinuto;
    private int metaHora;

    private final int velocidade = 1000;

    /**
     * Creates new form infoTimer
     */
    public TempoAlugado() {
        initComponents();

        Dimension tela = Toolkit.getDefaultToolkit().getScreenSize();

        this.setLocation(tela.width - this.getWidth(), 0);

//        int hora = ConnectionGuard.getInstance().getEstacao().getHour();
//        int minuto = ConnectionGuard.getInstance().getEstacao().getMinute();
//        int segundo = ConnectionGuard.getInstance().getEstacao().getSecond();
    }

    public void setValues(int hora, int minuto, int segundo) {
        metaHora = hora;
        metaMinuto = minuto;
        metaSegundo = segundo;

    }

    public String formatHora(int hora, int min, int sec) {
        String value = "";
        if (hora < 10) {
            value = "0" + hora;
        } else {
            value = hora + "";
        }

        if (min < 10) {
            value += ":0" + min;
        } else {
            value += ":" + min;
        }

        if (sec < 10) {
            value += ":0" + sec;
        } else {
            value += ":" + sec;
        }

        return value;
    }

    public void iniciarCronometro() {

        ActionListener action = new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                metaSegundo--;

                if (metaSegundo < 0) {
                    metaSegundo = 59;
                    metaMinuto--;

                }

                if (metaMinuto < 0) {
                    metaMinuto = 59;
                    metaHora--;

                }
                lblTempo.setText(formatHora(metaHora, metaMinuto, metaSegundo));

                if (metaHora <= 0 && metaMinuto <= 0 && metaSegundo <= 0) {
                    //stopTime();
                }
            }
        };
        this.timer = new Timer(velocidade, action);
        timer.setInitialDelay(0);
        this.timer.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTempo = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tempo Alugado");
        setResizable(false);

        lblTempo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N

        jButton1.setText("Deslogar-se");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(9, 9, 9)
                        .addComponent(lblTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(lblTempo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(223, 111));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ConnectionService conns = new ConnectionService();
        conns.setAction(Action.LOGOUT);

        ConnectionGuard.getInstance().sendToManager(conns);

        timer.stop();
//        
        setValues(00, 00, 00);
        
        Login.getInstance().setVisible(true);

        this.dispose();


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * this.
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TempoAlugado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TempoAlugado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TempoAlugado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TempoAlugado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TempoAlugado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private static javax.swing.JLabel lblTempo;
    // End of variables declaration//GEN-END:variables

}
