/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import controller.CaixaController;
import controller.LoginController;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
import java.text.NumberFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author JOSÉLUISFREIREDASILV
 */
public class AberturaCaixa extends javax.swing.JFrame {

    private String login = "";
    private float valorCaixa;
    private boolean telaLogin = false;
    private NumberFormat f = NumberFormat.getCurrencyInstance();
    private DecimalFormat  n = new DecimalFormat("#,##");

    public AberturaCaixa() {
        initComponents();
    }

    AberturaCaixa(String text) {
        initComponents();
        login = text;
        valorCaixa = new CaixaController().getValorCaixa();
        txtValorCaixa.setText(f.format(valorCaixa) + "");
    }

    AberturaCaixa(String text, boolean login) {
        initComponents();
        telaLogin = login;
        this.login = text;
        valorCaixa = new CaixaController().getValorCaixa();
        txtValorCaixa.setText(f.format(valorCaixa) + "");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnAbrir = new javax.swing.JButton();
        lblFechar = new javax.swing.JLabel();
        lblPular = new javax.swing.JLabel();
        txtValorCaixa = new javax.swing.JTextField();
        txtValorAtribuido = new javax.swing.JTextField();

        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder(new java.awt.Color(79, 158, 195), new java.awt.Color(46, 52, 59)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(230, 227, 231));
        jPanel3.setPreferredSize(new java.awt.Dimension(706, 706));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Abertura do caixa");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(223, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addContainerGap())
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 450, 60));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Atribuir valor: R$");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(103, 170, -1, -1));

        btnAbrir.setBackground(new java.awt.Color(255, 255, 255));
        btnAbrir.setFont(new java.awt.Font("Nirmala UI", 0, 14)); // NOI18N
        btnAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/caixaAbrir.png"))); // NOI18N
        btnAbrir.setText("Abrir Caixa");
        btnAbrir.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(204, 204, 204)));
        btnAbrir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAbrir.setIconTextGap(10);
        btnAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirActionPerformed(evt);
            }
        });
        jPanel1.add(btnAbrir, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 190, 40));

        lblFechar.setBackground(new java.awt.Color(255, 255, 255));
        lblFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/view/img/fechar.png"))); // NOI18N
        lblFechar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblFechar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblFecharMouseClicked(evt);
            }
        });
        jPanel1.add(lblFechar, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 20, 50, 40));

        lblPular.setBackground(new java.awt.Color(255, 255, 255));
        lblPular.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 18)); // NOI18N
        lblPular.setForeground(new java.awt.Color(51, 51, 51));
        lblPular.setText("Continuar sem abrir o caixa");
        lblPular.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPularMouseClicked(evt);
            }
        });
        jPanel1.add(lblPular, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 310, 240, -1));

        txtValorCaixa.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        txtValorCaixa.setForeground(new java.awt.Color(51, 51, 51));
        txtValorCaixa.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValorCaixa.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        txtValorCaixa.setDisabledTextColor(new java.awt.Color(51, 51, 51));
        txtValorCaixa.setEnabled(false);
        txtValorCaixa.setSelectionColor(new java.awt.Color(153, 153, 153));
        txtValorCaixa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorCaixaKeyTyped(evt);
            }
        });
        jPanel1.add(txtValorCaixa, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 100, 120, 40));

        txtValorAtribuido.setFont(new java.awt.Font("Nirmala UI", 0, 16)); // NOI18N
        txtValorAtribuido.setForeground(new java.awt.Color(51, 51, 51));
        txtValorAtribuido.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtValorAtribuido.setText("0.0");
        txtValorAtribuido.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(153, 153, 153)));
        txtValorAtribuido.setSelectionColor(new java.awt.Color(153, 153, 153));
        txtValorAtribuido.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtValorAtribuidoFocusLost(evt);
            }
        });
        txtValorAtribuido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtValorAtribuidoKeyTyped(evt);
            }
        });
        jPanel1.add(txtValorAtribuido, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 120, 40));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Nirmala UI Semilight", 0, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Valor no caixa: R$");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 110, 140, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(531, 367));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblFecharMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblFecharMouseClicked
        JOptionPane.showMessageDialog(null, "O caixa se encontra fechado, você pode abrir o caixa a qualquer momento para fazer movimentações", "ERRO", JOptionPane.WARNING_MESSAGE);
        TelaPrincipal.getInstance().TelaPrincipalLoginB(login, true);
        TelaPrincipal.getInstance().setVisible(true);
        this.dispose();

    }//GEN-LAST:event_lblFecharMouseClicked

    private void txtValorCaixaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorCaixaKeyTyped
        String carac = "0123456789.,";
        if (!carac.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_txtValorCaixaKeyTyped

    private void btnAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirActionPerformed
        float valor = 0;
        try {
            valor = Float.parseFloat(txtValorAtribuido.getText());

            if (new CaixaController().abrirCaixa(valor, login)) {
                new LoginController().logarADM(login);
                TelaPrincipal.getInstance().TelaPrincipalUser(login);
                        TelaPrincipal.getInstance().setVisible(true);
                this.dispose();
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Digite o valor corretamente!\n Exemplo: 1000,00.", "ERRO", JOptionPane.ERROR_MESSAGE);
            txtValorAtribuido.setText("0.0");
        }

    }//GEN-LAST:event_btnAbrirActionPerformed

    private void txtValorAtribuidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtValorAtribuidoKeyTyped
        String carac = "0123456789.,";
        if (!carac.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            btnAbrir.doClick();
        }
    }//GEN-LAST:event_txtValorAtribuidoKeyTyped

    private void txtValorAtribuidoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtValorAtribuidoFocusLost
        txtValorAtribuido.setText(txtValorAtribuido.getText().replaceAll(",", "."));
    }//GEN-LAST:event_txtValorAtribuidoFocusLost

    private void lblPularMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPularMouseClicked
        JOptionPane.showMessageDialog(null, "O caixa se encontra fechado, você pode abrí-lo para fazer movimentações!", "Atenção", JOptionPane.WARNING_MESSAGE);
        TelaPrincipal.getInstance().TelaPrincipalLoginB(login, true);
                TelaPrincipal.getInstance().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblPularMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AberturaCaixa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AberturaCaixa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AberturaCaixa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AberturaCaixa.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AberturaCaixa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAbrir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblFechar;
    private javax.swing.JLabel lblPular;
    private javax.swing.JTextField txtValorAtribuido;
    private javax.swing.JTextField txtValorCaixa;
    // End of variables declaration//GEN-END:variables
}
