/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.BancoDeHorasDAO;
import dao.UsuarioDAO;
import java.util.ArrayList;

import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import model.entidades.BancoDeHoras;
import model.entidades.Estacao;
import service.ConnectionManager;

/**
 *
 * @author gabriel
 */
public class IncluirTempoEstacao extends javax.swing.JFrame {

    private int hora;
    private int minuto;
    private int segundo;

    private int horaBanco;
    private int minutoBanco;
    private int segundoBanco;

    /**
     * Creates new form EditarTempoEstacao
     */
    public IncluirTempoEstacao() {
        initComponents();

        DefaultComboBoxModel modelo = (DefaultComboBoxModel) (jComboBoxEstacoes.getModel());

        ArrayList estacoes = ConnectionManager.getInstance().getEstacoes();

        for (int i = 0; i < estacoes.size(); i++) {
            if (((Estacao) estacoes.get(i)).getStatus().equals(Estacao.Status.LIVRE)) {
                modelo.addElement(((Estacao) estacoes.get(i)).getDescricao());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jComboBoxEstacoes = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        btn15m = new javax.swing.JButton();
        btn3h = new javax.swing.JButton();
        btn30m = new javax.swing.JButton();
        btn1h = new javax.swing.JButton();
        btn2h = new javax.swing.JButton();
        lblTempo = new javax.swing.JLabel();
        btnResetar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        btnConsultar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Incluir Tempo");

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Inclua o Tempo nas Estações de Uso.");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(22, 22, 22))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel3.setText("Estações de Uso Livres: ");

        jLabel1.setText("Incluir o Tempo: ");

        btn15m.setText("15m");
        btn15m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn15mActionPerformed(evt);
            }
        });

        btn3h.setText("3h");
        btn3h.setPreferredSize(new java.awt.Dimension(62, 25));
        btn3h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn3hActionPerformed(evt);
            }
        });

        btn30m.setText("30m");
        btn30m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn30mActionPerformed(evt);
            }
        });

        btn1h.setText("1h");
        btn1h.setPreferredSize(new java.awt.Dimension(62, 25));
        btn1h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn1hActionPerformed(evt);
            }
        });

        btn2h.setText("2h");
        btn2h.setPreferredSize(new java.awt.Dimension(62, 25));
        btn2h.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn2hActionPerformed(evt);
            }
        });

        lblTempo.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblTempo.setText("00:00:00");

        btnResetar.setText("Resetar.");
        btnResetar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetarActionPerformed(evt);
            }
        });

        jButton1.setText("Confirmar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxEstacoes, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn15m)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn30m)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn1h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn2h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btn3h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTempo)
                    .addComponent(btnResetar)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBoxEstacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn15m)
                    .addComponent(btn30m)
                    .addComponent(btn1h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn2h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn3h, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblTempo)
                .addGap(18, 18, 18)
                .addComponent(btnResetar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(24, 24, 24))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel4.setText("Consulte se Cliente possui tempo guardado no Banco de Horas:");

        jLabel5.setText("Informe o Usuário: ");

        txtUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUserActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar Banco de Horas");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addGap(3, 3, 3)
                        .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnConsultar))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnConsultar)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(15, 15, 15)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(596, 568));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn15mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn15mActionPerformed
        // TODO add your handling code here:
        setValues(00, 15, 00);
    }//GEN-LAST:event_btn15mActionPerformed

    private void btn30mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn30mActionPerformed
        // TODO add your handling code here:
        setValues(00, 30, 00);

    }//GEN-LAST:event_btn30mActionPerformed

    private void btn1hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn1hActionPerformed
        // TODO add your handling code here:
        setValues(01, 00, 00);

    }//GEN-LAST:event_btn1hActionPerformed

    private void btn2hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn2hActionPerformed
        // TODO add your handling code here:
        setValues(02, 00, 00);

    }//GEN-LAST:event_btn2hActionPerformed

    private void btn3hActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn3hActionPerformed
        // TODO add your handling code here:
        setValues(03, 00, 00);

    }//GEN-LAST:event_btn3hActionPerformed

    private void btnResetarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetarActionPerformed
        // TODO add your handling code here:
        resetValues();
    }//GEN-LAST:event_btnResetarActionPerformed

    private void txtUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUserActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUserActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        ArrayList estacoes = ConnectionManager.getInstance().getEstacoes();
        int indice = jComboBoxEstacoes.getSelectedIndex();

        if (this.hora + this.minuto + this.segundo > 0) {
            ConnectionManager
                    .getInstance()
                    .getEstacoes()
                    .get(indice).setHour(this.hora);

            ConnectionManager
                    .getInstance()
                    .getEstacoes()
                    .get(indice).setMinute(this.minuto);

            ConnectionManager
                    .getInstance()
                    .getEstacoes()
                    .get(indice).setSecond(this.segundo);
     }else{
          ConnectionManager
                  .getInstance()
                   .getEstacoes()
                   .get(indice).setHour(this.horaBanco);

            ConnectionManager
                    .getInstance()
                   .getEstacoes()
                    .get(indice).setMinute(this.minutoBanco);

            ConnectionManager
                  .getInstance()
                  .getEstacoes()
                    .get(indice).setSecond(this.segundoBanco);
               }

        
       System.out.println(ConnectionManager
                    .getInstance()
                    .getEstacoes()
                    .get(indice).getMinute());
       

    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:

        if ("".equals(txtUser.getText()) || txtUser.getText() == null) {
            JOptionPane.showMessageDialog(null, "Informe um nome de Usuário corretamente.");

        } else {
            int userId = new UsuarioDAO().getUserId(txtUser.getText());

            BancoDeHoras bancohoras = new BancoDeHorasDAO().selectByUser(userId);

            if (bancohoras.getTempo() > 0) {
                this.horaBanco = bancohoras.getHora();
                this.minutoBanco = bancohoras.getMinuto();
                this.segundoBanco = bancohoras.getSegundo();

                lblTempo.setText(formatHora(horaBanco, minutoBanco, segundoBanco));

            } else {
                JOptionPane.showMessageDialog(null, "O Cliente possui 00:00:00 em nosso banco de horas");
            }
        }


    }//GEN-LAST:event_btnConsultarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IncluirTempoEstacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IncluirTempoEstacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IncluirTempoEstacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IncluirTempoEstacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IncluirTempoEstacao().setVisible(true);
            }
        });
    }

    private void setValues(int hora, int min, int sec) {
        this.hora = hora + this.horaBanco;
        this.minuto = min + this.minutoBanco;
        this.segundo = sec + this.segundoBanco;

        lblTempo.setText(formatHora(this.hora, this.minuto, this.segundo));

    }
    
    private void resetValues(){
        this.hora = 00;  this.horaBanco = 00;
        this.minuto = 00;  this.minutoBanco = 00;
        this.segundo = 00;  this.segundoBanco = 00;

        lblTempo.setText("00:00:00");
    }

    public String formatHora(int hora, int min, int sec) {
        String value = "";
        if (hora < 10) {
            value = "0" + hora;
        } else {
            value = hora + "";
        }

        if (min < 10) {
            value += ":0" + min;
        } else {
            value += ":" + min;
        }

        if (sec < 10) {
            value += ":0" + sec;
        } else {
            value += ":" + sec;
        }

        return value;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn15m;
    private javax.swing.JButton btn1h;
    private javax.swing.JButton btn2h;
    private javax.swing.JButton btn30m;
    private javax.swing.JButton btn3h;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnResetar;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBoxEstacoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lblTempo;
    private javax.swing.JTextField txtUser;
    // End of variables declaration//GEN-END:variables
}
